Cm notebook
gomezzz/MSMatch pull request #40
Opened 2021-07-19 17:34 UTC by GabrieleMeoni

2021-07-19 17:36 UTC, GabrieleMeoni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a confusion matrix](https://trello.com/c/NngV9dwP/326-add-a-confusion-matrix)

2021-07-20 06:55 UTC, gomezzz requested changes

2021-07-20 06:55 UTC, gomezzz commented on datasets/eurosat_rgb_dataset.py
> +    def __init__(self, train, root_dir="/home/gabrielemeoni/project/SSLRS/data/EuroSAT_RGB/", transform=None, seed=42):
pls revert this

2021-07-20 06:55 UTC, gomezzz commented on datasets/ucm_dataset.py
> +        self, train, root_dir="/home/gabrielemeoni/project/SSLRS/data/UCMerced_LandUse/Images/", transform=None, seed=42, resize_to=(224, 224)
pls revert this

2021-07-20 06:55 UTC, gomezzz commented on utils.py
> +def plot_cmatrix(preds,labels,encoding, figsize=(8, 5),dpi=150, class_names_font_scale=1.2, matrix_font_size=12, save_fig_name=None):
could you add a docstring for this method?

2021-07-21 08:57 UTC, gomezzz approved these changes

2021-07-21 08:57 UTC, merged